### ISSUE TITLE
Loop displayed a temp basal over temp basal limit. 

### ISSUE THREAD

**Issue by loyalchallenger** [LoopKit/Loop#1339] opened 2020-06-26 02:56 UTC
![1FEAD146-45F2-420D-9332-D83684EB9482](https://user-images.githubusercontent.com/50498256/85815830-6505c400-b71e-11ea-8c61-8d7ed69a1d18.png)

**Describe the bug**
I expect to see the temp basal rate Loop is currently running. My temp basal limit is set to 0.6u/hr max. Loop displayed 1.30u/hr as running. 

**Attach an Issue Report**
Attached, just kidding. Apparently I can’t convert it to the right format to upload it from my phone.....

**To Reproduce**
Not sure how to reproduce. I’m running a temp basal override of 140%. I bolused for dinner and it showed up shortly after a second bolus for more food. It resolved after 5mins. 

**Expected behavior**
I would expect Loop to never display that a temp basal rate is running that is outside my limits. 

**Screenshots**
Screenshot attached.

**Phone**
 - Hardware: [e.g. iPhone 11 Pro]
 - OS Version: [e.g. iOS 13.3]

**Loop Version**
 - Version Number: [e.g. 2.2]
 - Repo: [LoopKit/Loop, master branch]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App]

**Pump**
 - Manufacturer: [Omnipod ]
 - Model: [eros]
 - Firmware version: [subg_rfspy 2.2/ble_rfspy 2.0]

**Additional context**
Thank you.

**Comment by Kdisimone** [comment] 2020-06-26 04:39
This is a known issue that has been logged in other GitHub issues previously. For short periods of time, sometimes loop may display a bolus in an equivalent high basal rate temporarily. Once Loop gets a fresh pump read and reconciles its data, the high basal rate will be corrected to accurately reflect it was a bolus dose instead of a high basal rate. 

I'll close this issue as it is a duplicate of prior similar issue.

**Closed by Kdisimone** 2020-06-26 04:39 UTC
