### ISSUE TITLE
Excessive insulin delivered

### ISSUE THREAD

**Issue by Trpl7ca** [LoopKit/Loop#1543] opened 2021-09-06 16:04 UTC
**Describe the bug**
I received more insulin than required to offset carbs. I was using watch to enter carbs and insulin. There were several times where watch would say not delivered retry. So I would select retry. Maybe it was delivering insulin but not reqistering on watch. Not sure but received almost 20units when only approximately 10 were needed.

**Attach an Issue Report**

file:///var/mobile/Library/SMS/Attachments/73/03/ACC53822-6247-4E4A-B3DE-3EDA3F34C9EC/Loop%20Report%202021-09-01%2019:28:38-07:00.md

**To Reproduce**
Unable to reproduce

**Expected behavior**
Only deliver insulin to offset entered carbs.

**Screenshots**

**Phone**
 - Hardware: IPhone 11 Pro
 - OS Version: 14.7 Is.1

**Loop Version**
 - Version Number: 2.2.5
 - Repo: https://github.com/Trpl7ca/LoopWorkspace

**CGM**
 - Device: G6
 - Manager app: Dexcom

**Pump**
 - Manufacturer: Omnipod
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by Trpl7ca** [comment] 2021-09-06 16:06
<img width="1772" alt="Screen Shot 2021-09-06 at 7 36 59 AM" src="https://user-images.githubusercontent.com/52380252/132242734-234400dc-27a0-4e33-9046-f808d16b76c4.png">
<img width="1603" alt="Screen Shot 2021-09-06 at 7 38 03 AM" src="https://user-images.githubusercontent.com/52380252/132242811-dcc652de-bc34-4080-a89e-7ad0ced294ac.png">
<img width="1599" alt="Screen Shot 2021-09-06 at 7 40 31 AM" src="https://user-images.githubusercontent.com/52380252/132242814-830e6800-7f85-42ae-8b46-9ebd1aee914e.png">

**Comment by Trpl7ca** [comment] 2021-09-06 16:08
[podState_Trpl7ca_20210901_1928_2.csv](https://github.com/LoopKit/Loop/files/7117071/podState_Trpl7ca_20210901_1928_2.csv)

**Comment by ps2** [comment] 2021-09-07 14:06
This looks like a duplicate of #1542?

**Closed by ps2** 2021-09-07 14:06 UTC
