### ISSUE TITLE
Feature: Open Loop Mode

### ISSUE THREAD

**Issue by taylorfowler** [LoopKit/Loop#257] opened 2016-11-14 21:19 UTC
Adding this to see how painful it would be to run Loop in "open loop mode". I use HAPP, and was trying to help out a new user who's using a MM 530G with Enlite CGM + MiniMedConnect to get their CGM data into nightscout. They were considering buying an android phone just to run HAPP. Seems super inconvenient to have to carry two devices. I don't do iOS development, but thought it might fill a need for people who don't have a compatible pump, but still want to be able to Loop. Thoughts?

**Comment by eugina32** [comment] 2016-11-18 16:59
I found the set up of this very easy and would love if this was an option as i don't have a compatible pump yet and would like to get to know the system on my two year old before I try to close the loop.

**Comment by dmelliott20** [comment] 2016-11-28 17:01
I would love this too!

**Comment by martijnmcb** [comment] 2016-11-28 18:44
Simulation mode would be great!

**Comment by jmatheson** [comment] 2017-05-18 22:35
Is there something missing in Loop open loop mode as it stands today?

**Comment by ps2** [comment] 2017-05-18 23:02
To do a HAPP style open loop mode, we would need to 1) allow input and editing of treatments (right now we just have a bolus command) and 2) allow loop to perform a prediction without requiring recent treatment data.

**Comment by osodebailar** [comment] 2017-12-12 08:46
In Android APS you can see how it will work with Open Loop. maybe you can get many ideas to integrate the mode in Loop.

**Comment by chrieke** [comment] 2019-01-05 18:06
Any updates on this? T1 toddler in the family with Minimed 640g + Enlite. Would it somehow be possible to download/stream Nightscout data (bs, bolus, basal etc.) to the Loop app and generate the Loop recommendations?

**Comment by Kdisimone** [comment] 2019-01-05 19:44
Open loop support for non-compatible pumps is not being worked on by anyone I am aware of. And no, would not be possible unless someone basically does massive work. I don’t see that happening.

**Comment by scottleibrand** [comment] 2019-01-05 20:31
As an alternative, you could also get an Android phone and run AndroidAPS, which has a “virtual pump” open loop mode.

**Comment by Kdisimone** [comment] 2019-10-14 04:36
Duplicate of https://github.com/LoopKit/Loop/issues/264

**Closed by Kdisimone** 2019-10-14 04:36 UTC
