### ISSUE TITLE
Shareclient server errors

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#1662] opened 2022-04-04 01:10 UTC
**Describe the bug**
way too often we get hours long red loops with (1) shareclient error messages and (while the transmitter ID is correctly entered. 

**Attach an Issue Report*

**To Reproduce*
Keep share client credentials in loop and transmitter ID. Wait until transmitter direct read fails for 15 minutes and loop falls back to share servers. 

**Expected behavior**
I expect that Loop would gracefully return to transmitter eavesdropping instead of staying stuck on a share client error message and red loop. 

**Screenshots**

![F0C28F93-5966-41BF-BA21-0ED678358BD5](https://user-images.githubusercontent.com/12402160/161458462-4bcb6e9f-2ca2-4e1d-a6a2-d956c369dbdd.jpeg)

IF YOU ARE EXPERIENCING THESE PROBLEMS, get issue reports from loop both before and after the red loop is resolved. Plus add **screenshots** and the info below;

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by Kdisimone** [comment] 2022-04-04 01:14
Please add your experiences , screenshots, and issue reports here

**Comment by marionbarker** [comment] 2022-04-04 07:28
This was fixed in dev only. See https://github.com/LoopKit/dexcom-share-client-swift/pull/25

**Comment by ps2** [comment] 2022-04-04 14:42
@marionbarker You are correct about the share error being fixed in dev only. There is different bug being highlighed here, but it's maybe a little subtle. The key part, and why it's good that @Kdisimone filed this (thanks!) is that when using the Dexcom G5/G6 integrations, the share error alone should be ignorable; i.e. share is just a backup for those BLE based integrations, and recovery of BLE comms should recover looping capability. So the bug here, that I want to look into, is not just the share error, but the problem of a share error causing the BLE side of things to break.

**Comment by marionbarker** [comment] 2022-04-04 15:45
Thanks for the explanation.  

If I understand you correctly, we're using this obvious error that shows up on many Loop-master user devices to assist in finding a different bug.  I was definitely confused by the request. I know a lot of people would love to have BLE issues diagnosed and fixed.

**Comment by ps2** [comment] 2022-04-04 15:59
Well, that's what is being reported, that the share error is *not* in fact innocuous and is causative for extended BLE outages. I have yet to see direct evidence of that, so I'm asking for help in gathering reports, and/or reproducing the issue.

**Comment by ALavoie89** [comment] 2022-04-04 19:55
ok, we have my 4y old son on loop using an OrangePro device on an iPhone XR, version iOS 15.3.1. We use the auto bolusing v2.2.4 with the Omnipod Eros pods, Dexcom G6, and the Dexcom App. We have had a red loop for over 2 hours now and there is no response from his current pod, nor are we able to dose insulin. I have issued a report that I will attach, I've restarted both the app and the phone itself, and deleted CGM data and then restored. I have tried restoring CGM data both with and without share data, and when adding Dexcom share data, I get another error similar to the one initially displayed by loop when trying to reconnect it. 

[Loop Report 2022-04-04 14_58_43-04_00.md
![IMG_4054](https://user-images.githubusercontent.com/102995851/161621508-bbabac24-e195-41d1-bc2b-5034c6c5aee7.JPG)
](https://github.com/LoopKit/Loop/files/8412725/Loop.Report.2022-04-04.14_58_43-04_00.md)
![Screenshot 2022-04-04 at 3 33 26 PM](https://user-images.githubusercontent.com/102995851/161621495-1215cd0b-ac33-458b-8c4a-47fb83dd1251.JPG)

**Comment by ps2** [comment] 2022-04-05 03:37
Thanks @ALavoie89, I've reviewed your issue report. I think this is a case of Loop reporting an unhelpful error. You were getting glucose just fine throughout this time. The actual problem preventing loop from completing was that your pod was not responding, and hadn't responded since 1:30pm.

**Comment by ps2** [comment] 2022-04-05 03:59
I spent a couple hours tonight reviewing code and trying to put master Loop into a state where it 1) Loses BLE comms 2) falls back to Share 3) gets the Shareclient.Shareerror "Failed to decode..." message. And then 4) recovers BLE comms.  I was able to perform those steps fine. Once BLE comms were back, Loop did try to Loop, and the first one failed (I had a pump comm error, most likely because I was using a 433 rl for a MDT pump), but the second one succeeded just fine. Tapping on the red loop did continue to show the shareclient error for a while.

My code review failed to produce any theories about ways that a share error could affect glucose readings over BLE, or prevent Loop from returning to normal looping once BLE comms are reestablished. My experiments above showed that at least for this type of comms outage, the share error did not prevent recovery in any way, although Loop did continue to show the error for a while, which I think could lead to more misunderstandings about what was really wrong (BLE outage).

I'm guessing that this error is gaining such notoriety and causing the share backfill feature to be blamed incorrectly mainly because of the visibility and persistence of this error messaging, and that it shows up when there is a problem. Pressing retry on a failed loop will often trigger the attempt to backfill, and show the error even when BLE CGM data is good, as can be seen in above issue report from @ALavoie89 

I'll backport the dexcom share fixes from dev into master and issue another point release. That will do nothing to solve the BLE outages, won't reduce the number of issues people are having, but it should help direct attempts to resolve the issues away from this red herring, and reduce or eliminate the reports of this error to our beloved support volunteers.

**Comment by dybs** [comment] 2022-04-05 04:59
> I'll backport the dexcom share fixes from dev into master and issue another point release. That will do nothing to solve the BLE outages, won't reduce the number of issues people are having, but it should help direct attempts to resolve the issues away from this red herring, and reduce or eliminate the reports of this particular error to our beloved support volunteers.

Does this backport include the fix for the change Dexcom made to the trend format in the Share data?  IIRC that fix was made in dev but not master yet.

**Comment by ps2** [comment] 2022-04-10 02:01
With the commits [here](https://github.com/LoopKit/dexcom-share-client-swift/commit/b0a6bd2e649f900b5928358662d1c77985ccaec3), this error should not mislead so many.

**Closed by ps2** 2022-04-10 02:01 UTC
