### ISSUE TITLE
Slowing refresh after Loop stayed for long time in background

### ISSUE THREAD

**Issue by francesc0-cgm** [LoopKit/Loop#762] opened 2018-07-21 15:28 UTC
Found this on iphone 5s and SE. after many hours loop stays in background, when opened, it takes many seconds to refresh and get usable. Commands are not working still status page has been refreshed. It happened in last dev (where ios 11 became mandatory) and seems not to be phone related.

**Comment by ps2** [comment] 2018-07-21 15:54
Duplicate of #597

**Closed by ps2** 2018-07-21 15:54 UTC
