### ISSUE TITLE
Loop double counting insulin on board

### ISSUE THREAD

**Issue by ngnrfsk** [LoopKit/Loop#1272] opened 2020-02-21 10:48 UTC
**Describe the bug**
After 3U bolus, with 0U IOB before, Loop thinks it has 6U IOB. 

**Attach an Issue Report**
[https://drive.google.com/file/d/1h8gVpv9wFnspcnfpbl-EzEt7_SdaJ6TS/view?usp=sharing](url)

**To Reproduce**
Have not noticed this behaviour before, but it’s a serious issue if correct. 

**Expected behavior**
Active Insulin showing as 3U.

**Screenshots**
[https://drive.google.com/file/d/1p0imy7gC7b6-kReiyH_1r7FAkY5T0Ofa/view?usp=sharing](url)

**Phone**
 - Hardware: iPhone 11 Pro
 - OS Version:13.3.1

**Loop Version**
 - Version Number: 2.0
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.4A1.1

**Additional context**

**Comment by gte731v** [comment] 2020-02-22 03:35
We had the same issue this morning.  Updated to Automatic-Bolus branch on 2/17, but we're were having this issue before on Dev.  This morning it didn't correct for about 30 min. after the bolus.

**Phone**
Hardware: iPhone 7
OS Version: iOS13.3

**Loop Version**
Repo: LoopKit/Loop (Automatic-Bolus)

**CGM**
Device: Dexcom G6
Manager app: Dexcom App

**Pump**
Manufacturer: Medtronic
Model: 523
Firmware version: 2.3A 1.1 0B 0B


[Loop Report 2020-02-21 08_36_21-05_00.zip](https://github.com/LoopKit/Loop/files/4238785/Loop.Report.2020-02-21.08_36_21-05_00.zip)
![IMG_0703](https://user-images.githubusercontent.com/41843670/75085754-53a37580-54fa-11ea-818f-8b35f3ad96ca.PNG)

**Comment by rolandet** [comment] 2020-02-22 18:13
One thing to check is to see if there is another app that has write access to Insulin Delivery in Apple Health. This happened to me once where an app that I installed had write access to Apple Health and was writing the Insulin Delivery so that it was picked up by the Loop app causing it to be double counted.

**Comment by arthiel16** [comment] 2020-03-23 19:19
This just happened to me too.  It fixed itself within about 15 minutes of the bolus. 

**Phone**
Hardware: iPhone 6
OS Version: iOS12.4.5

**Loop Version**
(forgive me -- I'm not 100% sure what info you need here
Loop V2.0
Repo: LoopKit/Loop (Master, built about 2 weeks ago)

**CGM**
Device: Dexcom G6
Manager app: Dexcom App

**Pump**
Manufacturer: Medtronic
Model: 722
Firmware version: 2.4A 1.1 0B 0B
[Loop-master (1).zip](https://github.com/LoopKit/Loop/files/4371468/Loop-master.1.zip)
![IMG_0004](https://user-images.githubusercontent.com/62225020/77354662-33412380-6d11-11ea-97b0-17f45d7421d4.PNG)
![IMG_0003](https://user-images.githubusercontent.com/62225020/77354665-34725080-6d11-11ea-943e-b608915e45d5.PNG)

**Comment by Kdisimone** [comment] 2020-03-23 19:39
This is more likely to be seen in open loop mode, but can happen in closed loop too. 

I've seen it when Loop misses a cycle. Will catch itself eventually...but still not visually easy to feel comfortable with.

**Comment by Kdisimone** [comment] 2020-03-23 19:40
Closing this issue as it's a duplicate of the one I already opened for it previously. 

https://github.com/LoopKit/Loop/issues/904

**Closed by Kdisimone** 2020-03-23 19:40 UTC
