### ISSUE TITLE
lost setting after iPhone reboot after iOS 13.2.2 update

### ISSUE THREAD

**Issue by skimaniac** [LoopKit/Loop#1176] opened 2019-11-13 16:51 UTC
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

When the phone reboot the setting in loop are not present. 
After stop the app and resart it from the app manager setting from NightScout and basal from the pump appear

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. reboot the phone
2. open loop app
3. stop loop app from app manager
4. restart loop app

**Expected behavior**
Before the update I do not lost my setting when the iPhone reboot.

**Screenshots**

![IMG_0881](https://user-images.githubusercontent.com/44727542/68784403-7cb68f00-060a-11ea-9b80-e413ea5e94d9.PNG)
![IMG_0880](https://user-images.githubusercontent.com/44727542/68784404-7cb68f00-060a-11ea-8c97-ce8ed5055cde.PNG)
![IMG_0879](https://user-images.githubusercontent.com/44727542/68784406-7cb68f00-060a-11ea-9c73-add7d661d468.PNG)
![IMG_0878](https://user-images.githubusercontent.com/44727542/68784407-7cb68f00-060a-11ea-9fad-3df75cb40a1c.PNG)
![IMG_0877](https://user-images.githubusercontent.com/44727542/68784408-7cb68f00-060a-11ea-9def-467199b35517.PNG)
![IMG_0876](https://user-images.githubusercontent.com/44727542/68784409-7cb68f00-060a-11ea-937c-f910135fefab.PNG)
![IMG_0875](https://user-images.githubusercontent.com/44727542/68784410-7cb68f00-060a-11ea-8732-ec087b384060.PNG)
![IMG_0874](https://user-images.githubusercontent.com/44727542/68784411-7d4f2580-060a-11ea-8d83-02b8f4d1801e.PNG)
![IMG_0873](https://user-images.githubusercontent.com/44727542/68784412-7d4f2580-060a-11ea-8c52-f4adf4cab51d.PNG)

[Loop Report 2019-11-13 11:28:13-05:00.log](https://github.com/LoopKit/Loop/files/3842371/Loop.Report.2019-11-13.11.28.13-05.00.log)

**Phone**
 - Hardware: [e.g. iPhone 7 Plus]
 - OS Version: [e.g. iOS 13.2.2]

**Loop Version**
 - Version Number: [1.10.1]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [Freestyle Libre]
 - Manager app: [Spike]

**Pump**
 - Manufacturer: [ Medtronic]
 - Model: [ 715]
 - Firmware version: [2.1A 1.1]

**Additional context**

**Comment by skimaniac** [comment] 2019-11-13 17:05
I also notice that the basal insuline did not show on the app screen

[Événement de pompe 3.txt](https://github.com/LoopKit/Loop/files/3842482/Evenement.de.pompe.3.txt)
![IMG_0883](https://user-images.githubusercontent.com/44727542/68786445-c94f9980-060d-11ea-982d-75894e5d3d89.PNG)

**Comment by Kdisimone** [comment] 2019-11-13 18:15
Closing as there is a duplicate of https://github.com/LoopKit/Loop/issues/1170

**Closed by Kdisimone** 2019-11-13 18:15 UTC

**Comment by skimaniac** [comment] 2019-11-13 18:38
I tried : ''This will then appear to the user as if settings have been deleted. Restarting Loop restores access to the settings.''

-my override setting do not comme back.
-still do not see basal on loop and no basal in apple Health

![IMG_0886](https://user-images.githubusercontent.com/44727542/68793100-9a8bf000-061a-11ea-8fef-07a12b96cc3f.PNG)
![IMG_0885](https://user-images.githubusercontent.com/44727542/68793101-9b248680-061a-11ea-9b8b-e739fc126713.PNG)
![IMG_8B2C4E784706-1](https://user-images.githubusercontent.com/44727542/68793153-b2637400-061a-11ea-92e3-0db8eefe99b6.jpeg)

**Comment by skimaniac** [comment] 2019-11-13 18:44
i also notice that when loop begin to communicate with the pump the basal appears (and the prediction line drop very low), and after few second the basal disappear and the prediction line comme to a better view

![IMG_0888](https://user-images.githubusercontent.com/44727542/68793713-7e3c8300-061b-11ea-9dcf-e94b8248c2aa.PNG)

![IMG_0889](https://user-images.githubusercontent.com/44727542/68793711-7e3c8300-061b-11ea-9774-e603875e950e.PNG)
