### ISSUE TITLE
IOB Miscalculation with autobolus 2.2.5

### ISSUE THREAD

**Issue by arlego** [LoopKit/Loop#1541] opened 2021-09-05 14:58 UTC
**Describe the bug**
Insulin delivered through autoboluses were NOT correctly added to IOB. Because of this, Loop kept giving AB after AB and NONE of them were added to IOB. IOB was a small negative number (around -0.8) and my son received more than **25** units over a one hour period before I realized what was happening. When I restarted his phone, IOB calculated properly and it predicted his BG to be -2,000. 

**Attach an Issue Report**
Trying to attach (but I’m not sure how). Also, with the shock of everything, I didn’t grab an issue report until about six hours after the incident. The IOB error happened from about 6 pm - 7 pm Pacific time on Sat 9/4. I have screenshots of the event history and the dashboard **AFTER** IOB was updated/calculated correctly (after his restart) but I didn’t grab a screenshot showing -IOB in the heat of the moment. Both NS and Loop showed -IOB (around-0.8) until his phone restarted but I don’t have photos/screenshots for that.

**To Reproduce**
- He entered several carb entries through his watch (two for dinner and one for desert) 
- I had him reduce the recommended insulin drastically because I was worried about a low and knew AB would help fill in missing insulin. 
- His IOB wasn’t updating properly. 
- He received AB after AB but IOB never increased. 
- I realized what was happening and restarted his phone. IOB finally calculated correctly and I opened loop and turned off AB strategy. 

**Expected behavior**
All insulin delivered (through basal, temp basals, boluses, or autoboluses) should be accounted for in IOB so IOB is accurate when used in Loop’s calculations. 

**Screenshots**

![F7B194C0-7D14-4740-9ADA-64F1C8245BD6](https://user-images.githubusercontent.com/67401428/132130648-0e395a95-0ecc-46a6-97ea-0bbd80f026f4.jpeg)
![66889AB0-EE24-46A7-B7C0-A55DCA61F142](https://user-images.githubusercontent.com/67401428/132130650-0da42d7b-c5b6-4fa2-8c32-045ba84d78fd.jpeg)

**Phone**
 - Hardware: iPhone XR
 - OS Version: 14.6

**Loop Version**
 - Version Number: 2.2.5
 
**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod 
 - Model: ???
 - Firmware version: ???

**Additional context**
1) We caught this and got lucky and he is fine but I shutter to think what would have happened if I hadn’t caught it so quickly, I wasn’t with him, or we didn’t have access to 200+ carbs. For now, I’ve disabled autobolus. I don’t feel comfortable turning it back on until we know why this happened and it’s resolved. 
2) His phone is locked using Screen Time but he has full access to use all apps needed for Loop and we’ve never had this issue before. All apps also have background refresh enabled. 
3) We were running AB before the switch to 2.2.5 when it was committed  to master and never had these issues.

**Comment by arlego** [comment] 2021-09-05 15:01
I have the issue report but am not sure how to attach. I’m in Safari. Do I need to be on my Mac or download the app to add the issue report? I can send directly to someone if they’re able to upload the issue report here for me.

**Comment by Trpl7ca** [comment] 2021-09-05 15:11
I believe I had the same thing happen the other day. I was using watch to enter carbs and bolus and ended up with over 20 units of insulin, way more than I needed. I thought it was somehow my fault but maybe not. I did not grab an issue report and have not seen a reoccurrence. Also 2.2.5

**Comment by Kdisimone** [comment] 2021-09-05 16:30
> I have the issue report but am not sure how to attach. I’m in Safari. Do I need to be on my Mac or download the app to add the issue report? I can send directly to someone if they’re able to upload the issue report here for me.

@arlego i can convert and post the Issue Report for you. Send it to Kdisimone@mac.com. 

Thanks.

**Comment by ps2** [comment] 2021-09-05 21:30
I really want to be able to dig into this issue but it's going to be difficult without a timely issue report. I really want to underscore how important it is to capture an issue report and screenshots while the problem is happening.  Issue reports are "snapshots" of the LoopState, not a history, and thus an issue report captured after the problem has resolved, will usually just look normal.

**Comment by Kdisimone** [comment] 2021-09-05 21:42
Here it is from @arlego 
[Issue Report 1541.pdf](https://github.com/LoopKit/Loop/files/7112393/Issue.Report.1541.pdf)

**Comment by arlego** [comment] 2021-09-05 21:46
@ps2 I understand but I want you to understand the scariness of the situation. BG of 54 ⬇️⬇️ With 25 IOB. We were away from home at someone else’s house for dinner when this happened. It took 250 g of carbs (we mixed sugar with water for him to drink), a mini gluc, and a zofran to get him stable. And, we had a second round 1-2 hours later when it was peaking. MY  first priority was to keep him conscious and stable. We, thankfully, didn’t have to go to the ER because I recognized the issue right away and calculated the insane amount of carbs he needed to combat the IOB. My husband and I were worried, in shock, and exhausted from the whole ordeal. The fact that I realized what was happening when his Dexcom was still reading in the 100s, saved us 5-10 minutes which probably made all of the difference in our outcome. 

I DID grab screenshots immediately after restarting loop and, as you can see, it gave him AB after AB and was predicting his BG to be close to -2,000 after the IOB was calculated correctly after the restart. I also ran the issue report because his pod was expiring and I wanted to make sure that was available to you and the other developers. 

Ok. After all that venting..... I did learn something new. I didn’t realize an issue report wasn’t for the life of the pod. So, in the future, I will try my best to also run the report in the heat of the moment. I just want you to know that documentation for research/resolution WAS on my mind and why I grabbed the screenshots that I did in the eye of the hurricane. I appreciate all the work that you and others do to bring us loop and continue to make improvements. But, this was scary. VERY scary. And my number one priority was keeping him safe (and alive). Think about a BG of 54 with 25 IOB for a minute....

**Comment by Trpl7ca** [comment] 2021-09-05 22:06
I got a report check above. Did not get screen shots as it was a social event and my purpose of using the watch was to be discreet. When the enormous amount of insulin was delivered I noticed and took issue report. Then headed to desert bar for 3 chocolate chip cookies and a piece of cake :) That worked and I never got below 65 so not as severe as arlego. As I recall I was blousing with watch and kept getting bolus failed and used the watch to retry. That happened several times so maybe that was a problem, Actually getting bolus but recognizing on watch. Again social setting trying not to be freaked. Thanks for you work, nothing is perfect and stuff happens.

**Comment by arlego** [comment] 2021-09-06 01:34
![D7EAD88C-0EF7-494F-B5DC-6466EADB5F04](https://user-images.githubusercontent.com/67401428/132148452-b4870a67-f531-4263-8971-095feab5b295.png)
 Here is a screenshot from NS before the IOB was updated on his phone after restart. It shows the calculation that his BG will be 646 and you can see all of the AB amounts and that IOB was -0.15. I’m happy to share my NS url with any of the developers privately and/or NS reports or Tidepool reports if that helps get you more information to look into the issue.

**Comment by arlego** [comment] 2021-09-06 01:37
![E41F5365-F87A-4842-92DE-DA720E7E4EC4](https://user-images.githubusercontent.com/67401428/132148594-e7a2bd6e-98ae-4adc-bee3-957ba773131e.png)

Here is the first screenshot from NS after IOB was updated properly.

**Comment by arlego** [comment] 2021-09-06 01:39
One last comment. He did eat about 90 g between the three entries so I would have expected about 7 units of insulin to treat this.

**Comment by ps2** [comment] 2021-09-06 01:47
@arlego Sorry if it seemed I was being judgemental about gathering the issue report; I didn't intend that at all. Totally understand that first priority is safety. My comment was intended to reiterate the importance of getting an issue report in the moment *if possible*. The issue report does have some historical data in it, but mostly it's a dump of the current state. I'm very glad you were able to catch it in time, and am doing what I can to figure out what went wrong. Thank you for reporting your experience; it helps everyone.

**Comment by ps2** [comment] 2021-09-06 01:50
@arlego Access to your NS instance to see what the Loop forecast was at those times of unexpected bolusing would be useful; I would like to see the devicestatus.json entries for those times. You can DM me on facebook or twitter with your url if that is ok with you.

**Comment by arlego** [comment] 2021-09-06 01:59
Thanks @ps2. I sent you the details through Facebook messenger. LMK if there’s anything else you need.

**Comment by marionbarker** [comment] 2021-09-06 06:03
I parsed both these log files to make sure the pod communication was OK.
I had to reformat the pdf file to make the ## Device Communication Log section readable by my parser. The other sections of the report may have extra \n characters.

Attached is:
* the reformatted Loop Report for @arlego (Loop Report 2021-09-05 06_42_13.md)
* the parsed csv file the pod for @arlego (podState_arlego_20210905_0642_1.csv) 
* the parsed csv file for the pod of interest (2nd one in report) for @Trpl7ca (podState_Trpl7ca_20210901_1928_2.csv)

Each row of the csv file interprets the HEX code from the message sent to or received from the pod.
(Time stamps are the GMT as found in the files.)
Because dosing strategy is Automatic Bolus, there are a number of sections with repeated 1a17 (bolus) requests, but I think I identified the sections of concern. (Ignore the part of the interpretation that says automatic is false - that's not being set yet in v2.2.5, it's a placeholder for the future when we'll be able to track whether it is a manual or automatic bolus request.)

For arlego: the repeated pattern of bolus requests (1a17) of concern starts and ends at GMT (local time is 7 hours earlier)
* 2021-09-05 00:54 (pod total delivery = 80.3 u, row 1617 in csv file)
* 2021-09-05 02:19 (pod total delivery = 111.9 u, row 1690 in csv file)

That's a total delivery of 31.6 units in just under 1.5 hours.

The pod messages appear normal.
Each 1a17, bolus request to pod, is followed by a status response from pod that indicates bolus request was received and then after the appropriate amount of time, the 0e, get status request has a response from the pod that the indicates the bolus completed.

For Trpl7Ca:  the repeated pattern of 1a17 of concern starts and ends at GMT (local time is 7 hours earlier)
* 2021-09-02 01:16 (pod total delivery = 35.25 u, row 717 in csv file)
* 2021-09-02 01:58 (pod total delivery = 54.70 u, row 758 in csv file)

That's a total delivery of 19.45 units in 42 minutes.

[Loop Report 2021-09-05 06_42_13.md](https://github.com/LoopKit/Loop/files/7113646/Loop.Report.2021-09-05.06_42_13.md)
[podState_arlego_20210905_0642_1.csv](https://github.com/LoopKit/Loop/files/7113652/podState_arlego_20210905_0642_1.csv)
[podState_Trpl7ca_20210901_1928_2.csv](https://github.com/LoopKit/Loop/files/7113655/podState_Trpl7ca_20210901_1928_2.csv)

**Comment by Trpl7ca** [comment] 2021-09-06 14:42
Nightscout reports attached. I added 48 carbs around 2000 for the cookies and cake eaten to change Loop projection from negative 400 or so.
<img width="1772" alt="Screen Shot 2021-09-06 at 7 36 59 AM" src="https://user-images.githubusercontent.com/52380252/132233793-d370b12d-8c20-4505-8133-805cd13ddf80.png">
<img width="1603" alt="Screen Shot 2021-09-06 at 7 38 03 AM" src="https://user-images.githubusercontent.com/52380252/132233812-2ed04e12-5e6d-48d8-9062-ccdebb230ae8.png">
<img width="1599" alt="Screen Shot 2021-09-06 at 7 40 31 AM" src="https://user-images.githubusercontent.com/52380252/132233823-1a39088f-1604-4b3f-a5a2-bb6e59128e39.png">

**Comment by ps2** [comment] 2021-09-06 14:44
I'm not done getting to the bottom of this, but heads up, until I figure out what's going on, it looks like it's related to having a very low (10%) override on for a while, followed by an unexpected fast rise. @Trpl7ca, I think it's likely that you have a different issue; perhaps you could move your report over to a new ticket?

**Comment by marionbarker** [comment] 2021-09-06 17:08
Pete. I have new pod on, running v2.2.5 with no customizations. Ready to test a scenario if you lay it out for me.

**Comment by ps2** [comment] 2021-09-06 21:46
This should be fixed in https://github.com/LoopKit/Loop/releases/tag/v2.2.6

**Comment by Kdisimone** [comment] 2021-09-06 21:47
Cool. Thank you @ps2 

does LoopWorkspace have the commits pulled in too?

**Comment by Kdisimone** [comment] 2021-09-06 22:07
@ps2 I just got off my butt to do a PR instead of leaving a comment...and you already have the commits checked in. Thanks.

**Comment by marionbarker** [comment] 2021-09-18 05:32
I believe this can be closed with the release of Loop v2.2.6

**Comment by arlego** [comment] 2021-09-18 05:41
@marionbarker I see an option to close with comment. Should I select that?

**Comment by marionbarker** [comment] 2021-09-18 15:24
Yes please.  I'm going to write a generic statement to drop in a few of these open issues.
Thanks so much for opening this issue to assist in finding and fixing this critical bug.

Only the author of the issue or the developers who own the repository have privileges to close an issue once it is opened. 
If you believe your issue has been resolved, please consider closing it (with or without comment) - that saves time for the developers.

**Closed** 2021-09-18 19:25 UTC
