### ISSUE TITLE
Negative prediction curve - incorrectly calculated after pre-meal target

### ISSUE THREAD

**Issue by woodduckie** [LoopKit/Loop#1006] opened 2019-07-06 01:50 UTC
**Describe the bug**
Loop went from "good" / reasonable projections to extreme negative (-650 mg/dL) after selecting the pre-meal target (80-80).

Based on current bg (239mg/dL), IOB (1.44U), COB (5g), carb ratio (9.9g/U), and ISF (185mg/dL/U), the projection is grossly incorrect.

Tried restarting app, restarting phone, etc. Without change. I see no duplicate bolus in loop history or apple health.

Once the predictions went off track, tried various overrides in an effort to drive a recalculation with less conservative targets / insulin requirements to no avail.

**Attach an Issue Report**
Issue Report attached.
[Loop Report 2019-07-05 17_52_44-05_00.zip](https://github.com/LoopKit/Loop/files/3364291/Loop.Report.2019-07-05.17_52_44-05_00.zip)

**To Reproduce**
First occurrence.  Have not been able to reset to "correct" projections to be in a position to replicate.

**Expected behavior**
Expected projection to remain constant, but loop increase aggressiveness with a lower target override.  Normal target during the day is 95-95.

**Screenshots**
![IMG_0070](https://user-images.githubusercontent.com/11234584/60749887-5438cd00-9f66-11e9-869b-cd55280a2762.png)

![IMG_0075](https://user-images.githubusercontent.com/11234584/60749885-5307a000-9f66-11e9-9f7d-8f7968dda1c5.jpg)

**Phone**
 - Hardware: iphone 6s
 - OS Version: 12.3

**Loop Version**
 - Version Number: 1.5.2
 - Repo: jojo

**CGM**
 - Device: Dexcom G6
 - Manager app: Spike

**Pump**
 - Manufacturer: Medtronic
 - Model: 523
 - Firmware version: 2.3A

**Additional context**

**Comment by woodduckie** [comment] 2019-09-23 16:43
Merged w/ #289 & resolved as far as I can see.

**Comment by woodduckie** [comment] 2019-09-25 18:53
Just had another example of projections being significantly lower than settings would dictate if calculated manually.  Loop projects -60 while manual calculations yield 441.  While there was some slight impact of glucose momentum & retrospective correction, but not 500 mg/dL.

"Running" override at 60% basal for 2 hours was canceled ~15 minutes prior to carb entry & bolus (and subsequent low projection).  After 



New device:
Phone
- Hardware: iphone XR
- OS Version: 13.0

Loop Version:
- v1.10.1-spike
- dev-spike repo as of ~9/19

Pump:
- Omnipod

![IMG_0394](https://user-images.githubusercontent.com/11234584/65630571-545fcc00-df9b-11e9-9722-9bb656ad801d.png)
![IMG_0395](https://user-images.githubusercontent.com/11234584/65630584-5a55ad00-df9b-11e9-8f4c-8786d506e83d.png)
![IMG_0396](https://user-images.githubusercontent.com/11234584/65630589-5cb80700-df9b-11e9-8eee-d2db8164dcd5.png)
![2019 0924 Loop Calcs](https://user-images.githubusercontent.com/11234584/65630731-94bf4a00-df9b-11e9-9c5c-c8caac317bcb.png)
[Loop Report 2019-09-24 191909-0500.txt](https://github.com/LoopKit/Loop/files/3654303/Loop.Report.2019-09-24.191909-0500.txt)

**Comment by ps2** [comment] 2019-09-25 19:15
Please do not open spike branch tickets here. It sounds like whoever did the spike integration is missing the fix for this.

**Closed by ps2** 2019-09-25 19:15 UTC

**Comment by woodduckie** [comment] 2019-09-25 21:49
I understand the desire to maintain separation with the spike branches - no worries.

From what I can see, the override functionality & the fix that was put in place was in the Loopkit repo.  The branch of Loop I'm using is current with Loop:dev and is pulling the same revision of Loopkit.

I'll chase down the integration as you suggest to validate more thoroughly.  That being said, I wouldn't discount the issue outright without consideration.

**Comment by ps2** [comment] 2019-09-25 23:22
I haven't heard any reports of this happening on dev since the fix. If you can reproduce this on dev, then please submit an issue report. Ideally built from a git checkout, so we can see the revision.
