### ISSUE TITLE
Loop Settings not loading

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#1170] opened 2019-11-04 16:27 UTC
If Loop is launched in the background (via bluetooth, for example) before the first unlock of the phone, UserDefaults will be unavailable, due to it being stored with a file access protection of NSFileProtectionCompleteUntilFirstUserAuthentication. 

This will then appear to the user as if settings have been deleted. Restarting Loop restores access to the settings, unless something triggers a write to settings before Loop is restarted.

**Comment by skimaniac** [comment] 2019-11-13 18:51
I tried : ''This will then appear to the user as if settings have been deleted. Restarting Loop restores access to the settings.''

-my override setting do not comme back.
-still do not see basal on loop and no basal in apple Health

![IMG_0886](https://user-images.githubusercontent.com/44727542/68793100-9a8bf000-061a-11ea-8fef-07a12b96cc3f.PNG)
![IMG_0885](https://user-images.githubusercontent.com/44727542/68793101-9b248680-061a-11ea-9b8b-e739fc126713.PNG)
![IMG_8B2C4E784706-1](https://user-images.githubusercontent.com/44727542/68793153-b2637400-061a-11ea-92e3-0db8eefe99b6.jpeg)

**Comment by skimaniac** [comment] 2019-11-13 18:52
i also notice that when loop begin to communicate with the pump the basal appears (and the prediction line drop very low), and after few second the basal disappear again and the prediction line comme to a better view

![IMG_0888](https://user-images.githubusercontent.com/44727542/68793713-7e3c8300-061b-11ea-9dcf-e94b8248c2aa.PNG)

![IMG_0889](https://user-images.githubusercontent.com/44727542/68793711-7e3c8300-061b-11ea-9774-e603875e950e.PNG)

**Comment by detroiterinnyc** [comment] 2019-11-15 03:08
I’m having this problem too. My full settings don’t restore. I’m guessing a rebuild is in my future.

**Comment by elnjensen** [comment] 2019-11-30 03:36
Got hit by this tonight and can confirm that not all settings come back.  Insulin model, carb ratios, sensitivities, and basal rates were correctly restored after restarting the app, but delivery limits, correction ranges, suspend threshold, and override presets were lost and had to be re-entered.

**Comment by ps2** [comment] 2019-11-30 13:36
Those will only be lost permanently if something is done to trigger a settings store before restarting Loop. Unfortunately, that’s pretty easy to do. Lots of actions, like enacting an override, can trigger that.

**Comment by loyalchallenger** [comment] 2019-11-30 13:53
I tried to build the reset transmitter app. It did not work on my new iPhone 11 Pro. I had to restart my phone for that and Loop lost all my settings. They did not come back when I relaunched Loop and I had to rebuild Loop to get my settings back.

**Comment by elnjensen** [comment] 2019-12-07 04:37
Despite trying to quickly quit and restart Loop when I encounter this, I’ve now lost my settings twice, simply from restarting my phone.

**Comment by yeagerm** [comment] 2019-12-08 16:42
> Got hit by this tonight and can confirm that not all settings come back. Insulin model, carb ratios, sensitivities, and basal rates were correctly restored after restarting the app, but delivery limits, correction ranges, suspend threshold, and override presets were lost and had to be re-entered.

I can confirm this problem. Three times now over the last two weeks or so. Latest LoopWorkspace/dev

**Comment by rolandet** [comment] 2019-12-08 16:58
@ps2 Any idea of how or when this will be fixed? My iPhone on 13.2.3 rebooted in the middle of the night and this obviously caused some issues for me without the config being loaded. This would appear to be a P1 issue.

**Comment by ps2** [comment] 2019-12-09 14:27
I have seen this happen a few times. Every time I've seen it happen, I've been able to get settings back by force-quitting Loop and starting it again. I'm not sure what is causing a settings save to be issued for those of you that are experiencing a more persistent loss of settings.

I'm also having trouble getting this to reproduce in a way that allows me to work on it.  Powering down, and waiting for a RL timer to kick off (once a minute), doesn't seem to do it.  Letting the battery drain, plugging it in, and waiting for the RL timer also doesn't kick it off.  Both of those failures point to Loop not actually starting until after unlock, which itself is a problem; Loop should be started after reboot, and before unlock, via RL timer. 

If anyone finds steps that reproduce this reliably, it would help with implementing a fix, or at least a workaround to reload settings from prefs when they become available.

**Comment by purplechap** [comment] 2019-12-09 15:08
Could that happen if users have the settings Software Update to Automatically Install Updates turned on? Maybe after an update the phone is in another status, that prevents settings from loading until the user has logged in again with their passcode.

**Comment by mtndev** [comment] 2019-12-09 16:08
I get this often, much more often than any restarts due to software update.
I'm not sure how to help you reproduce this, but I haven't seen a
correlation to software updates. It happens almost every time I restart the
phone, so I avoid restarting it at all costs. When I do have to restart and
it happens, I have to keep doing restarts until the data fully loads.
Sometimes it'll load no data, sometimes it's partial data. So if it's
partial data,  you have to either keep restarting or just re-enter whatever
was lost if it has enough data for loop to be green.

========
Robinson Business Development

https://robidev.com <http://robidev.com/>
val@robidev.com

LinkedIn?
http://www.linkedin.com/in/valerierobinson

**Comment by rolandet** [comment] 2019-12-09 16:57
Since updating to iOS 13.2.3 from 12.4 last week I’ve seen this twice. I’m not sure how repeatable these are but I’ll document them.

1. iPhone rebooted/crashed in the middle of the night and settings were not restored until I logged in the following morning.

2. Reboot iPhone
A. After reboot immediately logged in and      started Loop. All settings were missing.
B. Exited and killed Loop running in background.
C. Restarted loop and some of the settings were restored as previously mentioned. For example, Insulin model, carb ratios, sensitivities, and basal rates were correctly restored after restarting the app, but delivery limits, correction ranges, suspend threshold, and override presets were lost and had to be re-entered.

**Comment by ps2** [comment] 2019-12-10 15:56
Can anyone who has experienced this issue note what hardware they were running?  i.e. which iPhone/iPod model?  Also, which iOS version.

**Comment by mtndev** [comment] 2019-12-10 17:08
It happens for us about 80% of the time. 
iPhone SE
iOS 13.2 (kiddo is at school, so I can check if there's a 3rd number on the iOS release running)

**Comment by dirkgastaldo** [comment] 2019-12-10 17:20
iPhone XR
iOS 13.2
Happened a few times on 13.2.2.
Hasn’t yet happened on 13.2.3.

On Dec 10, 2019, at 9:08 AM, mtndev <notifications@github.com> wrote:

﻿

It happens for us about 80% of the time.
iPhone SE
iOS 13.2 (kiddo is at school, so I can check if there's a 3rd number on the iOS release running)

**Comment by rolandet** [comment] 2019-12-10 18:03
iPhone 8+
iOS 13.2.3

I did not see the issue when I was on iOS 12.4 FWIW.

**Comment by Kdisimone** [comment] 2019-12-11 17:40
@ps2 I can reliably reproduce using this:

put phone in Low Battery mode
shut down phone completely
restart phone, but not unlock it
wait about 10 min, unlock it but don't use an app (green light will still not be on in RL)
wait another 5 min or so, open Loop app and settings will be gone. 
restarting Loop app will bring back the settings.

I'm quite certain that I could probably eliminate some of the steps or streamline them (like maybe not have to wait 10 min? or 5 min?), but that's what I've done three times in a row that has worked to reproduce the issue and also give RL a chance to turn green light on if it were to want to.

I suspect this has a lot to do with Low Battery mode being on. That thing is a bugger.

**Comment by ps2** [comment] 2019-12-11 17:42
Thanks, those are the steps I've been trying in a variety of ways, but haven't tried with Low Battery mode being on. Will try that. Also, if you could capture a sysdiagnose from a session where it failed, that would be very helpful!

**Comment by Kdisimone** [comment] 2019-12-11 17:43
Sure can do. I assume with bt profile going? @ps2

**Comment by ps2** [comment] 2019-12-11 17:51
Yes, bt debugging might be important to capture what's going on here.

**Comment by Kdisimone** [comment] 2019-12-11 18:07
Watching a little closer...I do notice one interesting thing.

I restarted phone at 9:55am, didn't unlock it until 9:59. The green light on RL was off from 9:55 to 9:59. After entering the passcode at 9:59 to unlock-after-restart...the green light did come back on briefly. Then was turned off again maybe 10-15 seconds after it came on? So, looks like ios must be killing off the connection?

**Comment by Kdisimone** [comment] 2019-12-11 18:08
Sysdiagnose from that description above after I opened Loop app and saw settings were blank.

**Comment by ps2** [comment] 2019-12-11 18:09
And in that sysdiagnose settings were valid (not blank) before the phone was powered down, right?

**Comment by Kdisimone** [comment] 2019-12-11 18:10
@ps2 yes, the settings were showing before powering down. I'd installed BT profile. Restarted phone. Opened Loop to see the settings were visible. Then powered down phone in Low power mode

**Comment by Kdisimone** [comment] 2019-12-11 18:16
But just to triple check, I'll do it again and get another log. Can never be too sure lol

**Comment by Kdisimone** [comment] 2019-12-11 18:37
So, this time I didn't see the green light turn on even briefly during the process (maybe my eyes played tricks on me the previous time?). Anyways...here's another log from a settings blank. 

Restarted phone at 10:28 with enter-code-to-unlock phone...didn't use any apps, just let it sit
10:31 opened the phone again, opened Loop app...green light not on on RL, no settings in Loop.
Started log.

https://www.dropbox.com/s/8tgimw1azn9i2o2/sysdiagnose_2019.12.11_10-31-00-0800_iPhone-OS_iPhone_17B111.tar.gz?dl=0

**Comment by Kdisimone** [comment] 2019-12-11 18:39
Also, every time I am testing this, my dexcom G5 app is quite unhappy.  Perpetually stuck on this screen for G5 app now and makes a very annoying loud notification about it about a few minutes after the restart. Restarting the Dexcom app is not making it happy, unlike Loop's ability to recover.

![IMG_9168](https://user-images.githubusercontent.com/12402160/70649654-7532d780-1c02-11ea-93d0-ff1a10f2e5b4.PNG)

**Comment by Kdisimone** [comment] 2019-12-11 22:09
@ps2 also reproducible if Background App Refresh is turned off.

**Comment by Kdisimone** [comment] 2019-12-11 22:38
Crowd sourcing further info on Looped group, there is a fellow who says he had settings disappear (1) not on a reboot (2) using master 1.9.6 and (3) iOS 13.2.3. So obviously more than just low power mode and background app refresh potentially going on. And not confined to dev.

**Comment by mtndev** [comment] 2019-12-11 22:45
Further info on the hardware question, we had to turn off the fingerprint unlock (iPhone SE) about a month ago (fingerprint started not working and then we couldn't dose). This issue has  been since we unlock using code only. Not sure if that's related but in case it's helpful. This was happening on iOS 13.2.3 on dev.

**Comment by rachel1220** [comment] 2019-12-19 01:26
I have had loop delete all my setting 2 days in a row. Today it also deleted my Dexcom and omnipod. I did not turn off my phone. I was out skiing both days and came home to these issues. I am using an iPhone 11pro with iOS 13.2.2.

**Closed** 2022-12-07 15:31 UTC
