### ISSUE TITLE
Freeze on manual bolus over max

### ISSUE THREAD

**Issue by ihadanidea** [LoopKit/Loop#928] opened 2019-04-25 17:49 UTC
**Describe the bug**
Loop freezes and must be restarted when a manual bolus is entered that is above the max bolus limit. 

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Go to Bolus tool
2. Enter manual bolus amount of 0.1U over max bolus limit
3. Tap Deliver
4. The expected error message appears but cannot be released. Must restart app to clear.

**Expected behavior**
Manual bolus over max bolus limit should cause an error message which can be cleared by tapping Ok button or outside of message

**Screenshots**
<img width="455" alt="Screen Shot 2019-04-25 at 8 17 34 AM" src="https://user-images.githubusercontent.com/25700812/56749485-a96e8c00-6736-11e9-8bcc-9a4e344035af.png">

**Phone**
 - Hardware: iPhone XS, reproduced with iOS Simulator on iPhone XR
 - OS Version: 12.2

**Loop Version**
 - Version Number: 1.9.5
 - Repo: Omnipod-testing

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: 2.9.0

**Additional context**
First found in preparing testing drafts for Tidepool in Simulator. Replicated on 4/12 build of loop-priv, then on 1.9.5 Omnipod-testing branch. Issue report is from 4/12 build of loop-priv
[Loop Report 2019-04-25 08:42:20-07:00.txt](https://github.com/LoopKit/Loop/files/3118198/Loop.Report.2019-04-25.08.42.20-07.00.txt)

**Comment by vpdn** [comment] 2019-05-12 15:58
This is a duplicate of https://github.com/LoopKit/Loop/issues/946 and should be fixed by https://github.com/LoopKit/LoopKit/pull/276

**Comment by Kdisimone** [comment] 2019-10-09 20:48
addressed by the pr listed above. tested and confirmed

**Closed by Kdisimone** 2019-10-09 20:48 UTC
