### ISSUE TITLE
Crash when changing glucose safety limit

### ISSUE THREAD

**Issue by JohnKitching** [LoopKit/Loop#2129] opened 2024-02-11 09:15 UTC
**Describe the bug**
When glucose safety limit and pre-meal range are both set to 3.7 mmol/L tapping glucose safety limit crashes Loop. 

**Attach an Issue Report**

**To Reproduce**
Settings, glucose safety limit, set 3.7. 
Settings, pre-meal range, set both to 3.7
Settings, glucose safety limit
Loop crashes. 

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: iPhone 15 Pro max 
 - OS Version: iOS 17.3.1 

**Loop Version**
 - Version Number: Dev 3.3.0
 - Repo: LoopKit browser build

**CGM**
 - Device: Libre 2
 - Manager app: LibreLink to start sensor only

**Pump**
 - Manufacturer: Omnipod 
 - Model: Dash
 - Firmware version: 4.1.0

**Additional context**

**Comment by marionbarker** [comment] 2024-02-11 19:19
Please close this issue. This has already been reported and there is a PR waiting for review.
* Issue #1864 was closed by the bot
* [LoopKit PR 476](https://github.com/LoopKit/LoopKit/pull/476) has been tested and fixes this issue

**Comment by ps2** [comment] 2024-02-19 01:01
Duplicate of https://github.com/LoopKit/Loop/issues/1864

**Closed by ps2** 2024-02-19 01:01 UTC
