### ISSUE TITLE
Thread 1: signal SIGABRT issue when loading onto iPhone

### ISSUE THREAD

**Issue by sepuku** [LoopKit/Loop#1268] opened 2020-02-11 21:00 UTC
I upgraded to iOS 13.3.1 today, and as I'm using a free developer account, also happened to be the day I needed to rebuild the app. Decided to do both on the same day.

The build of the application works fine, and a build and run in the iPhone 11 Pro Max (my device) simulator also works fine, however on the physical device when attempting to launch the app, I get 2x "Thread 1: signal SIGABRT" errors within Xcode, and the screen on the device stays black. It looks like its actually launching the application, but there is nothing on screen other than the time (top left), signal/battery details (top right), and the swipe up to return home line (bottom).

Unable to attach an issue report as I can't launch the application to submit one.

**Expected behaviour**
Expecting the application to launch successfully, but it doesn't get any further than the details above.

**Screenshots**
<img width="1512" alt="Screenshot 2020-02-11 at 18 35 44" src="https://user-images.githubusercontent.com/8983275/74278212-c77e9a80-4d10-11ea-8784-f2482182db63.png">

<img width="1512" alt="Screenshot 2020-02-11 at 21 01 36" src="https://user-images.githubusercontent.com/8983275/74278847-c26e1b00-4d11-11ea-8ccb-ebb23b7fa5aa.png">

![61CEA83B-9956-41E6-9901-214E81601307](https://user-images.githubusercontent.com/8983275/74278254-d6654d00-4d10-11ea-8ae9-759fb1a010f2.png)

**Phone**
 - Hardware: iPhone 11 Pro Max
 - OS Version: 13.3.1 (note: the screenshot above shows my device name being beta. It is **not** running a beta version of iOS, and hasn't been since iOS 13 went GM)

**Loop Version**
 - Version Number: 2.0 build 57
 - Repo: Loopkit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom app

**Pump**
 - Manufacturer: Omnipod
 - Model: Unsure of model/NA
 - Firmware version: Unsure

**Comment by Kdisimone** [comment] 2020-02-12 00:24
Closing this out as it is related to https://github.com/LoopKit/Loop/issues/1264

We will track the free account issues there with iOS 13.3.1

**Closed by Kdisimone** 2020-02-12 00:24 UTC

**Comment by sikandarali307** [comment] 2020-09-20 09:44
i alsoo have same error but i havent to solve this problem

**Comment by david-gonzalez-pnw** [comment] 2021-05-03 17:00
@sikandarali307, or anyone else, did you find a workaround or root cause for this issue?

I followed the conversation in https://github.com/LoopKit/Loop/issues/1264 and tried some of the suggestions but nothing has helped there. Personally that issue is specific to what the original post was about, specifically _The maximum number of apps for free development..._ 

I also followed the very specific step in https://loopkit.github.io/loopdocs/build/build_errors/#abort-with-payload, but the parent directory nor the carthage checkout folder are located in an iCloud mapped drive. To be sure I moved the files to a different parent directory and still ended up with the same error
<img width="1172" alt="Screen Shot 2021-05-03 at 12 59 29 PM" src="https://user-images.githubusercontent.com/44993471/116907396-7d345280-ac0f-11eb-8657-6134ec631445.png">

**Comment by Jose-13m** [comment] 2022-11-11 02:32
Hello, in the little experience I have, several things have worked for me:
1 remove the app
2 close the simulator
3 close Xcode
4 with the use of POD/SDK check that the distribution configuration has YES, in Build Settings. a) check if the POD/SDK reference is not lost. b) Check that the POD/SDK you use is in Embed & Sing in the general configuration.
I hope it works for you
