### ISSUE TITLE
Can't clear "Exceeds Maximum Bolus" warning without closing/reopening the app

### ISSUE THREAD

**Issue by seanknox** [LoopKit/Loop#985] opened 2019-06-05 22:04 UTC
**Describe the bug**
If a bolus amount is entered that is larger than the defined bolus delivery limit, the "Exceeds Maximum Bolus" modal that appears can't be dismissed.

**Attach an Issue Report**
(Can provide, ask)

**To Reproduce**
1. Set a bolus delivery limit of any number, e.g. 5
2. Enter a bolus amount larger than the delivery limit, e.g. 6
3. Loop displays "Exceeds Maximum Bolus" modal that can't be dismissed. Touching any part of the screen has no effect.

**Expected behavior**
I should be able to dismiss the max bolus warning by either touching or swiping the screen.

**Screenshots**
![IMG_13D95DED80BF-1](https://user-images.githubusercontent.com/1231630/58993656-0122fd00-87a3-11e9-9109-15eedec21a6e.jpeg)

**Phone**
 - Hardware: iPhone XR
 - OS Version: iOS 12.2

**Loop Version**
 - Version Number: v1.10.0dev
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod (Eros)

**Comment by loudestnoise** [comment] 2019-06-05 22:13
I believe this was resolved by this [commit](https://github.com/LoopKit/LoopKit/pull/276)

**Comment by seanknox** [comment] 2019-06-05 23:01
How do apply that LoopKit update in my Loop repo?

**Comment by Kdisimone** [comment] 2019-06-05 23:21
Since you are just using normal Loop branch omnipod-testing, you just have to download the code fresh and rebuild. If you have your own cartfile edits (although your posts indicates you don’t), then you’d probably want to cherry-pick instead

**Comment by Kdisimone** [comment] 2019-06-05 23:22
The carthage update in new loop download folder in Terminal app will fetch the updated Loopkit

**Comment by greglongo518** [comment] 2019-07-18 02:13
I downloaded the omnipod-testing branch from the link on the loopdocs page after this fix should have been in, and also just downloaded the jojo-beeps branch, and this issue seems like it is still there.    I fixed it locally on my build by simply adding the line alert.addCancelAction() in the file Loop->View Controllers -> BolusViewController.swift after the alert for "Exceeds Maximum Bolus" is created and before the call to present(alert, animated:true), and that seems to resolve it.   I am not sure if the problem is that the previous fix didn't work or that somehow I am still not pointing to the updated loopkit, but my first download of loop was only 2 weeks ago, and the issue was still present.

**Comment by Kdisimone** [comment] 2019-07-21 16:00
Can you screen shot the commit hashes that `carthage update` is bringing in and also post your cartfile from the loop folder that you are building in so that I can double check the commit with the fix is actually being pulled in?

**Comment by Kdisimone** [comment] 2019-07-21 16:01
But @greglongo518 I also know my jojo branches have not been updated with that fix. The commit history should show that. I typically only update my branches when Loop does releases. Not commit by commit.

**Comment by Kdisimone** [comment] 2019-10-09 19:58
resolved by commit noted above.

**Closed by Kdisimone** 2019-10-09 19:58 UTC
