### ISSUE TITLE
Delay in Loop getting Spike data

### ISSUE THREAD

**Issue by ggirling** [LoopKit/Loop#764] opened 2018-07-24 09:23 UTC
Currently there appears to be a lag between Spike's readings and those recognised by Loop, which is likely to make course correction of BS more difficult.  A Facebook posting on the Looped page outlines the issue here:
https://www.facebook.com/groups/TheLoopedGroup/permalink/2068106700072652/?comment_tracking=%7B%22tn%22%3A%22O%22%7D

**Comment by Kdisimone** [comment] 2018-07-24 17:05
A couple comments:  

1.  Issues with Spike integration will not be addressed within Loop releases.  Spike is not officially supported by Loop, nor intended to be in the future.

2.  I've read through the issues that you have linked in the FB group and I still think that the issue is misunderstood.  The watch complications are not an indication of the most current info being used within the Loop app.  You commented in FB "the issue is that the phone and watch are relaying on the same, older data, pulled from the cloud, rather than Spike's more recent data."  <--that is incorrect  The cloud on the BGs when using Spike app are an indication that Spike is using an internal server.  It is not fetching "from the cloud".  So, if there are delays in your Loop app ON THE PHONE then that would affect your Loop responsiveness...but the delay would not be coming as a result of fetching data "from the cloud" but rather a failure on the internal server setup with Spike.  Looking at the Spike and Loop app on the phone (not the watch) would be the appropriate comparison of the timing of bg data.  Hope that helps.

I'm going to close the issue here since Spike isn't supported by Loop and this does not appear to be a Loop issue.  If you want to tag me in the facebook post to discuss further, I'd be happy to answer any follow-up questions there.

**Closed by Kdisimone** 2018-07-24 17:05 UTC
