### ISSUE TITLE
Missing Bolus Prompt After Entering Carbs on Apple Watch 6.0.1

### ISSUE THREAD

**Issue by justingshreve** [LoopKit/Loop#1139] opened 2019-10-09 05:00 UTC
**Describe the bug**
After being tricked into upgrading to iOS 13.1.2 and Apple Watch 6.0.1, there are no prompts to bolus after entering carbs on the Apple Watch. I can bolus on the phone, but the watch emits a chime, but then returns to main screen. When I click on bolus, there is no suggestion either. I usually go to phone and suggestion exists there. It should prompt me to bolus, like it previously did before upgrade. Additionally, I'm noticing missing notifications in some other apps, so this seems to be a change in functionality on the Apple side, but figured I'd submit issue nonetheless.

**To Reproduce**
1. Go to 'Loop on Apple Watch'
2. Click on 'Carbs'
3. Enter an amount and then `Add Carbs`
4. Hear chime, but no bolus prompt.

**Phone**
 - Hardware: iPhone Xs Max
 - OS Version: iOS 13.1.2
- Apple Watch 4 on 6.0.1

**Loop Version**
 - Version Number: omnipod-testing

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom

**Pump**
 - Manufacturer: Omnipod

**Comment by primags** [comment] 2019-10-10 16:35
I'm experiencing the same issue

**Comment by marylarsen** [comment] 2019-11-13 03:14
I have the exact issue with my Apple Watch 2 after updating to 6.0.1.

**Comment by Nightfoxy** [comment] 2019-11-13 03:35
I experienced the same thing the first few carb entries and a handful sporadically since the update. Usually I see a bolus recommendation when I press the bolus button on the watch though.

Branch: Dev 1.10.1 
iPhone 7 
Watch series 2

**Comment by wyckojr** [comment] 2019-11-13 03:37
Same issue here. I've had to switch away from using the Apple Watch to bolus. I'm on the omnipod-testing branch.

**Comment by justingshreve** [comment] 2019-11-13 07:29
I just reinstalled loop through xcode and now it is working again. I did pull down latest two commits and changed the target OS version when I installed, but other than that, not sure what did it, but it is working again for me!

**Comment by yogevcardiac** [comment] 2022-01-16 19:37
It's relevant for me, exact same scenario. Using brand new Apple watch SE (OS 8.3) and iPhone12 Pro. Using FreeAPS branch.

**Comment by ps2** [comment] 2022-01-17 18:17
I believe this is working in the dev branch. Closing. If it happens again, please reproduce and attach xcode logs or sysdiagnose logs, along with the exact time the issue was reproduced, so I can correlate it in the logs. Thanks!

**Closed by ps2** 2022-01-17 18:17 UTC

**Comment by Nightfoxy** [comment] 2022-01-17 19:15
@ps2 can this be patched to master? Everyone that updated to watch os 8 has this issue.
Or, do you know which commit fixed it?

**Comment by yogevcardiac** [comment] 2022-01-18 07:28
@ps2 I use freeAPS branch, got the latest code and it's still reproduced.
Maybe some of the maintainers needs to cherrypick the commit of this fix?
