### ISSUE TITLE
”.” Instead of ”,”

### ISSUE THREAD

**Issue by claraloop** [LoopKit/Loop#940] opened 2019-04-29 11:26 UTC
**Describe the bug**
When installing on iPhone 5s iOS 12.1 Swedish  language swedish keyboard there Will be no ”,” in loop resulting in not being able to give bolus (unless even units) it also produces a round (up) error if typing 1.6 that’ll result in 2,0. (Max bolus max basal etc)

“Work around” I removed Swedish keyboard replacing with English. That did not solve issue.
I changed phones language to English that resolved the issue.

But preferably it should work with “.” As well as “,” or force it to be “,”

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
Others tried to set language and keyboard to Swedish but did not succeed in replicating issue unless it was already on the phone. 

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: IPhone 5s
 - OS Version: iOS 12.1

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, omnipod branch 

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: omnipod 
 - Model: Eros 
 - Firmware version: 

**Additional context**

**Comment by benfiscal** [comment] 2019-04-29 18:47
A work around for me was to set the "Region setting" to USA.

**Comment by yuri-zhuk** [comment] 2019-05-06 10:06
Same issue with Russian, iPhone 7, iOS12.2.
Localisation is fine in other places, but not on the bolusing form.

**Comment by vpdn** [comment] 2019-05-12 14:51
Anyone can add more details how to reproduce the error? I can have a look, but don't see the error. Setting the region to swedish shows a proper "," in my case.

![Simulator Screen Shot - iPhone 5s - 2019-05-12 at 16 49 55](https://user-images.githubusercontent.com/387312/57583929-09568800-74d6-11e9-8610-625dbe5b2fd7.png)

**Comment by reelman** [comment] 2019-05-24 19:21
Since I'm using Loop - so it's 1.9.3 version I haven't got this type off issue. Only thing is that placeholder says "0.0" instead of "0,0" for my locale.

**Comment by yuri-zhuk** [comment] 2019-06-05 10:34
> Anyone can add more details how to reproduce the error? I can have a look, but don't see the error. Setting the region to swedish shows a proper "," in my case.
> 
> ![Simulator Screen Shot - iPhone 5s - 2019-05-12 at 16 49 55](https://user-images.githubusercontent.com/387312/57583929-09568800-74d6-11e9-8610-625dbe5b2fd7.png)

The phone language in my case is set to Russian, and on this screen instead of ',' there is '.' on the keyboard. The bolus with '.' (such as '1.6') is not accepted. I suspect changing the phone language to English would fix this, but cannot try now - not near my kid. Anyway, her phone needs to stay in Russian.

I'd appreciate if someone could at least point me to the place in the code where this view is implemented. This is a real pain in cases when no bolus is recommended, and I need to make a fractional one anyway.

**Comment by reelman** [comment] 2019-06-05 10:40
![IMG_FF8A14A20676-1](https://user-images.githubusercontent.com/2168153/58950392-fb232100-878e-11e9-88ab-2b7635a5aeb2.jpeg)
Looks fine for me or am I wrong.

**Comment by yuri-zhuk** [comment] 2019-06-05 10:43
Wierd. I'll have another look tonight and try to provide more details. Can you actually administer a bolus, e.g. 0,1?

**Comment by reelman** [comment] 2019-06-05 10:45
Yes, all is OK. I can't even enter dot. 
I would go with the new version if yours is old. I'm on 1.10.0dev

**Comment by yuri-zhuk** [comment] 2019-06-05 12:29
We're on master 1.9.4, I believe. Could be the reason.

**Comment by Kdisimone** [comment] 2019-06-05 14:06
I have found iOS is a bit glitchy on keyboard selections sometimes if you’ve had a language installed.  Even if you switch back to a different language, sometimes the old language’s keyboard still appears randomly. The solution is that you have to go into your iPhone settings and remove the old language’s keyboard. Changing languages doesn’t delete the keyboard, and sometimes that old keyboard just gets used. 

When I was testing translations for loop a lot, my keyboard would often be in Spanish or Chinese when using other apps, even if my language was set to English again. It’s an iOS thing.

**Comment by yuzhuk** [comment] 2019-06-05 16:59
Ok, I’ve done some testing and the issue is pretty simple:
It looks like iOS always selects the English keyboard if it’s present under Keyboards in Settings -> General, and so there’s always ‘.’ in the bolus dialog.
If I remove the English keyboard leaving only the Russian one, then it presents the latter and I get the ‘,’ and can enter a fractional bolus.

Weird, since it works find in other dialogs...

**Comment by yuzhuk** [comment] 2019-06-05 17:40
Ok, I jumped the gun on my conclusions. Just now I went to bolus her and it’s magically fine even with both keyboards in settings. So yeah, as Katie said it’s iOS taking it’s time to sort it out.
That said, the order of the keyboards is now reversed with the Russian above English - that’s probably what’s making it work now.

**Comment by Kdisimone** [comment] 2019-10-09 20:57
@yuzhuk you can set your keyboard preferences in iphone settings, General, Keyboards and then select edit. That will shows three horizontal lines on the right side of each keyboard row, and you can drag the row you'd like to be the first choice to the top of your list. Sounds like everything is addressed, so I'll close this issue now.

**Closed by Kdisimone** 2019-10-09 20:57 UTC
