### ISSUE TITLE
Temporary double-counting of bolus in IOB

### ISSUE THREAD

**Issue by elnjensen** [LoopKit/Loop#845] opened 2018-11-02 00:12 UTC
In some circumstances, Loop will record a bolus as delivered *and* it will record the reservoir change for that same bolus, resulting in that bolus insulin being counted twice in the active insulin.  This eventually reconciles itself (presumably after a successful history pull from the pump), but in the short term it is both alarming to the user and leads to incorrect low-temping until it is corrected. 

I've seen this twice now.  Attached is a screenshot from the most recent time, along with an issue report.  You can see the high-rate basal spike along with the bolus symbol.  My max basal is 3.5u / hour, so the spike with a larger rate than that reflects a bolus.   I did a 3.0-unit bolus at 22:23 UTC, which you can see reflected in the reservoir drop in the issue report, and also in the bolus history there.   Not sure why this double-counting is occurring.   I've seen the bolus-as-large-basal-spike in the past (and suggested some code in #777) but haven't seen this double-counting (the large basal spike *and* the bolus triangle) until recently. 

As I said, it does eventually reconcile itself, but this was 18 minutes after the bolus, so that's a bit longer than I might expect. 

I'm running 1.9.4 dev with a 522 pump, and have Event History set as the preferred data source.   Issue report is [here](https://www.dropbox.com/s/shtfjaokmkdifm4/Loop%20Report%202018-11-01%20184149-0400.md?dl=0).    (GitHub doesn't seem happy about the .md file extension.) 

I also saved an issue report last time I saw this, two weeks ago.  That report is [here](https://www.dropbox.com/s/hn3srjnqef1s14w/Loop%20Report%202018-10-17%20125248-0400.md?dl=0).  Let me know if you want a screenshot as well. 

![img_3062](https://user-images.githubusercontent.com/2545845/47886403-31bb4680-de10-11e8-9acb-9c22a5a959e3.png)

**Comment by francescaneri** [comment] 2018-11-09 16:31
@ps2 encountered the same error as possible to merge to verify?

**Comment by mpangburn** [comment] 2018-12-02 00:55
Here's a couple reports of the same issue from ~3 weeks ago that I forgot I had saved. Exported as PDFs because GitHub doesn't allow direct attachment of Markdown files for some reason.

[Loop Report 2018-11-10 132851-0800.pdf](https://github.com/LoopKit/Loop/files/2636479/Loop.Report.2018-11-10.132851-0800.pdf)
[Loop Report 2018-11-11 102228-0800.pdf](https://github.com/LoopKit/Loop/files/2636480/Loop.Report.2018-11-11.102228-0800.pdf)

**Comment by rumil** [comment] 2019-02-19 17:50
I don't know if I am hitting the exact same issue but last few days I've seen Loop temporarily doubling IOB even way after bolus. This happened at least a few times.

There are two factors, which might have exposed the issue for me (recent changes):
1. Update to Loop 1.9.4-katie from 1.9.3 (where I don't think I've ever seen it)
2. Switch to FIASP profile (started a few days ago and running open Loop since then to tweak ratios)

Below you can find 2 screenshots and 2 issue reports taken about 2h after bolus, one loop apart.
In the first screenshot Loop reports 14,55U IOB (defiantly not true) and in the second it changes to 6,66U IOB (right one)

Doubled IOB:
![img_1585](https://user-images.githubusercontent.com/4641980/53035792-88f42e00-3476-11e9-8775-144fbe72169a.PNG)
[Loop Report 2019-02-19 14:56:07+01:00.txt](https://github.com/LoopKit/Loop/files/2881267/Loop.Report.2019-02-19.14.56.07%2B01.00.txt)

Fixed on next Loop:
![img_1586](https://user-images.githubusercontent.com/4641980/53035853-b0e39180-3476-11e9-9719-9572814668e1.PNG)
[Loop Report 2019-02-19 15:02:20+01:00.txt](https://github.com/LoopKit/Loop/files/2881275/Loop.Report.2019-02-19.15.02.20%2B01.00.txt)

**Comment by Kdisimone** [comment] 2019-02-19 18:22
@rumil Your's looks like the first image was a recently rebooted Loop app after a failure...issue report shows a failed loop and the UI also is indicative a loop that hasn't really run yet after a reboot.  Graphics and data after a reboot, and before the first loop has run, are usually outdated and need a chance to reconcile. After your loop ran, the UI and data were figured out correctly and the reboot was cleared of its rebooted-UI issues.

**Comment by rumil** [comment] 2019-02-19 18:32
I've been getting this quite often recently, even just now it happened again. Is there a way I can confirm it's iOS killing Loop in the background?

**Comment by Kdisimone** [comment] 2019-02-19 20:50
@rumil According to the Issue reports, your last error was a Radio Comms failure (interference that prevented pump from giving a good read to RL).

**Comment by Kdisimone** [comment] 2019-02-19 20:53
@rumil also, I found that restarting phone after upgrading to 1.9.4 helped.

**Comment by chbra** [comment] 2019-03-05 14:59
Also experienced this today. I have the issue report as well if needed.
Carbs were entered and suggested bolus of 2.3 given. Added some carbs straight after without giving another bolus.
Had to fetch pump history to show the correct IOB

![image2](https://user-images.githubusercontent.com/19237737/53814171-6de9e980-3f5f-11e9-8851-5f145b31d7d3.png)
![image3](https://user-images.githubusercontent.com/19237737/53814181-6fb3ad00-3f5f-11e9-88f4-4ea11d51d42e.png)
![image4](https://user-images.githubusercontent.com/19237737/53814190-717d7080-3f5f-11e9-8d1c-2fc212f51c7b.png)

**Comment by DConmy** [comment] 2019-04-08 12:21
I've seen this several times with the 1.95 master version.

For me, it resolves itself fairly quickly.   I had bolused 10 units, which was showing in the UI as both a bolus (triangle) and a very high temp basal.   I took screenshots, and it resolved itself several seconds later.   I had not thought of grabbing an issue report.   This may be different than the other reports, since I would suspect that the pump operations would have been read at the same time.   It would appear that the processing of the pump operations applied the reservoir change before the basal operation and only later reconciled the 2.   It is a small window, but does appear to happen more frequently than in the past.

Running...
commit 7b819ea0682220ec5be71ab65919033e8ea2cd7f (HEAD -> master, tag: v1.9.5, origin/master, origin/HEAD)
Author: Pete Schwamb <pete@schwamb.net>
Date:   Wed Mar 27 20:19:33 2019 -0500

**Comment by reelman** [comment] 2019-05-20 13:52
Hi guys,
I think we still struggling with this issue. This might lead us to wrong decisions if we are not aware of it.
![UNADJUSTEDNONRAW_thumb_41f9](https://user-images.githubusercontent.com/2168153/58026644-32e76300-7b17-11e9-9cbc-b500da33d415.jpg)

https://www.facebook.com/groups/TheLoopedGroup/2268283606721626/?comment_id=2268304016719585

**Comment by timmy354321** [comment] 2019-05-20 19:28
I am getting this double counting while running the simulator. So far I've had one that has not resolved itself after 3 hours! I'm wondering if this is a simulation related issue or if I should expect this bug with the riley link running.

**Comment by ryangs23** [comment] 2019-05-24 02:05
I have noticed this same issue while running with a simulated pump, but someone on the Zulip chat reports experiencing it with a real pump, so it's probably not unique to the simulator.

So far I believe I only see it with boluses greater than 2 units. A 2 unit or smaller bonus is recorded correcly in IOB, but a 2.5 unit bolus shows up as 5.

My rough guess on time it takes this to resolve itself is 2 or 3 hours. I will pay attention and see if it's consistent, or related to an action of some sort.

**Comment by timmy354321** [comment] 2019-05-24 17:11
I've been able to force a correction by issuing a bolus of 0.001 units. it's not really a fix but it gets the loop up and running again!

**Comment by ryangs23** [comment] 2019-05-28 00:31
Seems like you can also fix it by force quitting the app and restarting it.

**Comment by ryangs23** [comment] 2019-05-30 19:25
I just saved issue reports from before and after restarting the app, so with double-counting and then without. Would it help to share those?

This is a nearly all-time, constant problem for me. I will be curious to see if that persists after I switch from the simulator to a real RileyLink and OmniPod.

**Comment by sascha-egerer** [comment] 2019-06-19 05:13
I have the same problem using the simulator pump. Bolus is always count double until I force quit the app.

**Comment by ryangs23** [comment] 2019-07-08 21:22
Luckily, I have not encountered this issue since switching from the simulated pump to an actual Omnipod.

**Comment by ps2** [comment] 2019-08-18 03:02
This should happen much less frequently on dev now.

**Comment by naromero77** [comment] 2019-09-02 05:14
Does this only occur with boluses? This evening I saw the BG prediction curve changed suddenly from a believable trajectory to an eventual BG of only 4, this was following by immediate zero TB. This happened after I adjusted Loop parameters (ISF, basal, IC). (parameters were only changed by 10-16%). This happened on a fork of dev that has IRC. The super low BG persisted for about 10-15 minutes. I decided to toggle the IRC to off and the BG prediction suddenly became much more reasonable. I turned IRC back ON and they things behaved as they should. I only have NS website recordings of this incident.

**Comment by ps2** [comment] 2019-10-02 15:10
@naromero77 Were you using overrides on a branch other than recent dev? There was an issue with recently turned off overrides causing very low predictions, that is now fixed in dev. In any case, this issue is about double boluses. I think the temporary double bolus tracking issue is also mostly alleviated in dev, and am closing this issue since I haven't heard of anyone having this issue recently.

**Closed by ps2** 2019-10-02 15:10 UTC

**Comment by naromero77** [comment] 2019-10-02 15:16
@ps2 It was one of Dragan's branches that had IRC.

I have not see this issue in a while and I have been running a recent dev. Its fine to close.
