### ISSUE TITLE
In Open Loop the app overrides zero temping set by user if the BG starts rising and above target

### ISSUE THREAD

**Issue by xpucuto** [LoopKit/Loop#543] opened 2017-08-01 09:14 UTC
While I was sick I noticed that Loop even in Open mode has overridden my zero temp basal with normal when the bg has started to rise . I wasn't able to eat anything so going little higher wasn't a problem for me. 
I hope I don't experience suck sickness soon to reproduce it but will probably have the chance to test this after giving birth end of the month. 

<img width="382" alt="screen shot 2017-07-26 at 22 25 37" src="https://user-images.githubusercontent.com/11740423/28818010-95235846-76b2-11e7-9288-244acbfee93f.png">

**Comment by xpucuto** [comment] 2017-08-01 09:15
Here is the full view of the day 
<img width="1008" alt="screen shot 2017-07-26 at 22 25 43" src="https://user-images.githubusercontent.com/11740423/28818197-16a91f2c-76b3-11e7-8130-6dc79465713e.png">

**Comment by Kdisimone** [comment] 2018-03-22 00:02
@xpucuto have you still noticed this behavior?  I haven't seen my loop start any temp basals or override any existing temp basals when in open loop mode.  Perhaps I don't understand what it is that you were observing?

**Comment by xpucuto** [comment] 2018-03-22 00:04
No Katie . I haven’t used the open loop lately .

**Comment by Kdisimone** [comment] 2018-10-17 20:28
perhaps the recommendation was accidentally clicked on to accept?  closing this issue as we don't have more info to go on at this point, and i haven't been able to reproduce this in testing. @xpucuto if you see this behavior again, feel free to open this issue back and we can dig in deeper while the issue is happening.

**Closed by Kdisimone** 2018-10-17 20:28 UTC

**Comment by xpucuto** [comment] 2018-10-17 20:42
Ok I will . For now everything is perfect ;) thank you :)
