### ISSUE TITLE
Bolus Confirmation Notification (BCN)

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#270] opened 2016-11-21 11:00 UTC
What if you could get a notification to confirm the bolus not only when it fails, but also in the time of delivery? For my daughter and teachers would be very helpful. thanks Matteo
 It could be a solution to the issue # 255 @trixing.
#131 @amazaheri Are you still interested?

**Comment by ps2** [comment] 2016-11-22 14:27
This is a duplicate of #131

**Closed by ps2** 2016-11-22 14:27 UTC
