### ISSUE TITLE
Double Bolus Actually Delivered

### ISSUE THREAD

**Issue by carolezell** [LoopKit/Loop#1434] opened 2020-11-13 20:23 UTC
I’ve been looping for a year and 8 months and just experienced a first - an unintentional double bolus. I went to bolus for lunch via loop,  got the “bolus failed to deliver” message and noticed a red loop. Loop recognized the carbs so it of course predicted I’d go high. So I waited a few minutes, then hit the correction icon (double orange arrows at bottom of loop app). It suggested the exact amount I had tried to bolus originally and I tapped it and accepted the delivery of insulin. Then the graph predicted I’d go super low. I figured the display would straighten itself out, then saw loop showed two blouses, not one. I decided to check the bolus history on the pump and sure enough it actually bolused twice. Now that I’m full of apricot preserves to cover bolus number 2 on top of my lunch and thought it would be good to share here.  Attaching screen shots and photo of pump screen and loop issue report. I'm on IOS 14.0.1.  Pump data and loop version are attached in photos.

[Loop Report 2020-11-13 122109-0700.pdf](https://github.com/LoopKit/Loop/files/5539134/Loop.Report.2020-11-13.122109-0700.pdf)

Let me know if more info is needed. 
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.  

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

![IMG_7211](https://user-images.githubusercontent.com/59322041/99116549-70646980-25b1-11eb-9985-fd398d2bd6a3.jpg)
![IMG_7212](https://user-images.githubusercontent.com/59322041/99116559-72c6c380-25b1-11eb-8693-e422ac57e5ec.PNG)
![IMG_7210](https://user-images.githubusercontent.com/59322041/99116562-735f5a00-25b1-11eb-8f3d-2cb16cf764ee.PNG)
![IMG_7209](https://user-images.githubusercontent.com/59322041/99116564-73f7f080-25b1-11eb-8b4e-df824c87bf09.PNG)

**Comment by Kryptonit3** [comment] 2020-11-19 23:26
Literally just happened to me. The app was red loop so I bolused manually for carbs and would fix red loop later, waited a few seconds and got failed bolus. Then I tried again but looked at pump. It was delivering bolus. So i canceled it half way through thinking the first one went through and it did. Second bolus also popped up failed bolus. Second bolus says 1.6 but would have been 2.0 if I didn't cancel it.

On 2.2.4 AB branch. Built AB branch on 10/12/20 and just rebuilt today to make sure it wasn't certificate issue. App opens, then hangs and crashes to a black screen spinning white wheel. When I try to get to the Report Issue screen it locks up and just says "Loading...". The app hangs and is in a crash state and doesn't show carbs, iob or BG data.


![image](https://user-images.githubusercontent.com/72818445/99736164-ebd38880-2a93-11eb-8a6a-2bfe3577ffcd.png)

![image](https://user-images.githubusercontent.com/72818445/99736241-13c2ec00-2a94-11eb-8550-f50b484c78f3.png)

![image](https://user-images.githubusercontent.com/72818445/99736383-453bb780-2a94-11eb-8454-8d292d468c1f.png)

Tried to look at debug console but all it says is "Message from debugger: Terminated due to signal 9".

Again, app worked fine for weeks. This is not a certificate issue. Also got a "Glucose Data Not Available" message and to check CGM source but going into CGM settings shows it sees the G6 and a recent reading.

![image](https://user-images.githubusercontent.com/72818445/99736543-8d5ada00-2a94-11eb-86ec-0ff08980a35d.png)

![image](https://user-images.githubusercontent.com/72818445/99736593-a794b800-2a94-11eb-815f-75befc4e6537.png)

Is this a Health app issue?

**Comment by bewest** [comment] 2022-12-08 22:05
Is this an ongoing issue?  Are there any hints on reproducing?  Is this potentially unique to Medtronic pumps?  Is this fixed by 2.2.6?

**Comment by ps2** [comment] 2022-12-22 18:06
This is an issue in dev. It's actually a different issue in dev, but the symptoms are pretty much the same, so I'm keeping this as the tracking ticket for the issue.

**Closed** 2023-08-07 20:37 UTC
