### ISSUE TITLE
Loop v3.2 Dexcom G7 Page is in Spanish

### ISSUE THREAD

**Issue by awahbah** [LoopKit/Loop#1952] opened 2023-03-18 04:15 UTC
**Describe the bug**
Loop v3.2 Dexcom G7 Page is in Spanish. Language settings on device are set to English

**Attach an Issue Report**
[Loop Report 2023-03-17 21:10:37-07:00.md](https://github.com/LoopKit/Loop/files/11007425/Loop.Report.2023-03-17.21.10.37-07.00.md)

**To Reproduce**
1. Go to Settings
2. Click on Dexcom G7
3. Scroll down to anywhere
4. See page in spanish

**Expected behavior**
Page should be in english

**Screenshots**
![IMG_0249](https://user-images.githubusercontent.com/7147285/226084208-17bf98f7-2819-4413-9da3-7e1f2a675ca8.PNG)

**Phone**
 - Hardware: iPhone 14 Pro Max
 - OS Version: iOS 16.3.1

**Loop Version**
 - Version Number:v 3.2
 - Repo: Loop

**CGM**
 - Device: Dexcom G7
 - Manager app: Dexcom
 
**Pump**
 - Manufacturer: Insulet
 - Model: Dash Pod
 - Firmware version: 4.10.0

**Comment by ps2** [comment] 2023-03-18 16:22
Thanks for reporting. Closing this as a duplicate of #1951

**Closed by ps2** 2023-03-18 16:22 UTC
