### ISSUE TITLE
Request for Recommended bolus alerts

### ISSUE THREAD

**Issue by jsisaacson** [LoopKit/Loop#1256] opened 2020-01-31 17:14 UTC
I have a suggestion for the developers.  I would love to get alerts for recommended boluses.  As an example, I was at my desk at work with BG of 80. I entered lunch carbs into Loop but got no recommended bolus because my suspend is 77, which is all fine and good.  The problem was that I then got absorbed in something I was working on and a client called and, well, 90 minutes later I was at 250 and had a recommended bolus sitting there waiting for me.  An alert on my Apple Watch and/or on my phone screen would have headed that off. 

BTW, thank you for this fabulous tool.

**Comment by TanyaSpencer** [comment] 2020-01-31 17:18
I agree.  This would be great!!

Have a great day,
Tanya

On Jan 31, 2020, at 9:15 AM, jsisaacson <notifications@github.com> wrote:

﻿

I have a suggestion for the developers. I would love to get alerts for recommended boluses. As an example, I was at my desk at work with BG of 80. I entered lunch carbs into Loop but got no recommended bolus because my suspend is 77, which is all fine and good. The problem was that I then got absorbed in something I was working on and a client called and, well, 90 minutes later I was at 250 and had a recommended bolus sitting there waiting for me. An alert on my Apple Watch and/or on my phone screen would have headed that off.

BTW, thank you for this fabulous tool.

**Comment by jrodloop** [comment] 2020-01-31 18:07
This could be useful for me at times.

On Jan 31, 2020, at 12:18 PM, TanyaSpencer <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree. This would be great!!

Have a great day,
Tanya

On Jan 31, 2020, at 9:15 AM, jsisaacson <notifications@github.com<mailto:notifications@github.com>> wrote:

﻿

I have a suggestion for the developers. I would love to get alerts for recommended boluses. As an example, I was at my desk at work with BG of 80. I entered lunch carbs into Loop but got no recommended bolus because my suspend is 77, which is all fine and good. The problem was that I then got absorbed in something I was working on and a client called and, well, 90 minutes later I was at 250 and had a recommended bolus sitting there waiting for me. An alert on my Apple Watch and/or on my phone screen would have headed that off.

BTW, thank you for this fabulous tool.

**Comment by mgunns** [comment] 2020-01-31 19:34
Yes, this would be excellent.

**Comment by NightScoutForSeb** [comment] 2020-01-31 19:42
This would be great!


Hanna SandovalSent from Yahoo Mail for iPhone


On Friday, January 31, 2020, 11:34 AM, mgunns <notifications@github.com> wrote:

Yes, this would be excellent.

**Comment by lindseyaparker** [comment] 2020-01-31 19:48
Same thing has happened to us more times than I’d like to admit.  I would
love this feature!  Thank you!

**Comment by MrBennington** [comment] 2020-02-01 15:23
Upvote from me 👍

**Comment by Kdisimone** [comment] 2020-02-01 16:14
Duplicate of https://github.com/LoopKit/Loop/issues/344

**Closed by Kdisimone** 2020-02-01 16:14 UTC
