### ISSUE TITLE
Loop will sometimes crash when removing reservoir history

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#368] opened 2017-01-12 04:04 UTC
Not always, but often Loop will crash when removing reservoir history, usually around when I get close to 30mins worth)

The crash is visisble as the app closing fully, similar to killing it in IOS task view.

**Comment by Kdisimone** [comment] 2018-10-18 19:10
I've been trying to reproduce this issue/failure with Loop 1.9.3 and cannot reproduce.  Has the issue resolved for you @beached ?

**Comment by Kdisimone** [comment] 2018-11-29 23:53
Closing as the issue no additional information has been provided to indicate the issue has continued to be a problem.  Please reopen if the issue has continued and add logs if possible.  Thanks

**Closed by Kdisimone** 2018-11-29 23:53 UTC
