### ISSUE TITLE
v2.3.0 Dev - Autobolus does not sound end beep

### ISSUE THREAD

**Issue by rfmurphy81** [LoopKit/Loop#1645] opened 2022-03-21 02:41 UTC
**Describe the bug**
In Extended mode for Confidence Reminders, Loop does not appear to have the pod beep when ending an autobolus. However, manual boluses beep at the start AND the end as expected. This has happens for both Eros and Dash pods. 

**Attach an Issue Report**
See attached

**To Reproduce**
1. Enable Extended under Confidence Reminders
2. Enter a few fake carbs to initiate an autobolus on the next loop

**Expected behavior**
In Extended mode, the pod should beep when the autobolus has finished. The beep behavior works as expected in v.2.2.6 master. 

**Screenshots**
N/A

**Phone**
 - Hardware: iPhone 13 Pro
 - OS Version: iOS 13.2.1

**Loop Version**
 - Version Number: v.2.3.0
 - Repo: LoopWorkspace Dev from March 9

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: OmniPod
 - Model: Dash AND Eros
 - Firmware version: 4.10.0

**Additional context**
N/A

[Loop Report 2022-03-20 19:22:28-07:00.md](https://github.com/LoopKit/Loop/files/8312763/Loop.Report.2022-03-20.19.22.28-07.00.md)

**Comment by marionbarker** [comment] 2022-05-03 20:21
This feature is by design.

When making a manual bolus, it is probably a significant amount and therefore hearing the ending as well as the beginning beep is useful.

When Loop is providing automatic bolus - these are probably every 5 minutes when BG is rising.
* By hearing the starting beep - you get an audible clue that AB are being issued
* The boluses tend to be smaller when automatic and it was thought adding the ending beep would not be helpful

Coming from an earlier version of Loop, you may remember getting an ending beep as well as a beginning beep for automatic bolus. That was because there was no mechanism for the part of the code that sets up the beep pattern to know whether it was a manual or automatic bolus.  With Loop-dev, that mechanism exists.  Therefore, the beeping can be configured to beep at the beginning for automatic bolus and to beep at beginning and end for manual bolus.

**Comment by itsmojo** [comment] 2022-05-06 07:55
When the Loop-dev pump managers could first tell the difference between automatic & manual boluses, automatic boluses were made not to beep at all because they generated so many beeps that most users could not leave Confirmation Beeps enabled. Later an additional beep mode was added to optionally provide automatic bolus beeps, but it was limited to only beep at the start of an automatic bolus to prevent beep fatigue from having two generally close sets of beeps for each automatic bolus potentially every 5 minutes.

If a user desires to have both sets of beeps for each automatic bolus when enabled, the user would have to edit the one call to session.bolus() in OmniBLE/OmniBLE/PumpManager/OmniBLEPumpManager.swift (for Dash) or in rileylink_ios/OmniKit/PumpManager/OmnipodPumpManager.swift (for Eros) to have the same argument for the completionBeep parameter as the acknowledgementBeep parameter.

**Comment by rfmurphy81** [comment] 2022-09-17 20:23
Looks like it had changed a few months ago. It seems like the completionBeep stopped for the automatic boluses (but they still happen for manual boluses). Plus, I noticed that a sort of acknowledgement beep happens when Loop changes the basal rate. Is anyone able to help me figure out where to enable the completionBeep for automatic boluses (or disable the basal rate change beeps)?

**Comment by itsmojo** [comment] 2022-09-18 06:46
The easiest modification to enable completion beeps for automatic boluses when in extended mode would be to change the line that initializes the completionBeep let variable to `let completionBeep = acknowledgementBeep` in the enactBolus() function (in OmniKit/PumpManager/OmnipodPumpManager.swift for Eros and in OmniBLE/PumpManager/OmniBLEPumpManager.swift for Dash). The temp basal beep behavior is separate of the bolus beeping behavior.

**Comment by rfmurphy81** [comment] 2022-09-18 20:05
Hi Joe,

THanks for the prompt reply. I found the following links in under that function but wanting to confirm the correct action.

Current:
```
        let acknowledgementBeep = self.beepPreference.shouldBeepForCommand(automatic: activationType.isAutomatic)
        let completionBeep = beepPreference.shouldBeepForManualCommand && !activationType.isAutomatic
```
Change To:
```
        let acknowledgementBeep = self.beepPreference.shouldBeepForCommand(automatic: activationType.isAutomatic)
        let completionBeep = acknowledgementBeep
```
Is that correct or did I totally boof it?

**Comment by ps2** [comment] 2022-11-09 19:47
Closing as observed behavior is as expected.

**Closed by ps2** 2022-11-09 19:47 UTC
