### ISSUE TITLE
AutoSense for Loop

### ISSUE THREAD

**Issue by ddaniels1** [LoopKit/Loop#429] opened 2017-04-03 06:59 UTC
Anyone notice Loop behavior as resistance increases, high temps for a while, then zero temps as it thinks you will blow past your target downwards, then starts high temping again when that doesn't happen? Wonder if we can use this to our advantage to build an autosense algorithm into loop?

Opposite happens as sensitivity increases, low temp causes negative iob to build, assumes you will go up, once predicted glucose reaches target range cancels the low temp, if you are very sensitive, won't go up, starts dropping again and then loop again low temps. BG guard helps here, but same idea.

One approach is to exclude any data within say 3 hours of a carb announcement. Then in these carb free periods one could set the integral of the glucose and insulin data for say 2 hours and calculate ISF.  Of course this would have problems when eating pasta or pizza, but perhaps the exclusion could be based on if there are any COB according to set absorption times or better yet dynamic carb absorption mode...

**Comment by scottleibrand** [comment] 2017-04-03 15:28
What you're describing is approximately the algorithm used by (OpenAPS) autotune to calculate ISF. It turns out it's actually more difficult than you'd expect to get "clean" ISF data without purposeful ISF testing: most meals transition gradually from a situation where carb absorption determines the deviations from predicted insulin activity to a long tail where ISF matters. But deciding where to transition to calculating ISF actually makes a huge difference in how much bias the algorithm has toward detecting false-positive sensitivity vs. resistance, or simply not having any data to calculate ISF at all. 

Because of that, and because autotune can already be used by Loop users, I think the next step would be to replicate something like the OpenAPS autosens algorithm for use inside Loop.  That algorithm doesn't attempt to calculate ISF independently in real time, which is quite hard, but instead calculates whether overall insulin sensitivity is higher or lower in terms of its affect on both ISF and basal rates.  This allows us to calculate a ratio that can be used to adjust both the assumed underlying basal (for calculating IOB for example) and the ISF simultaneously.  This allows us to use the data from overnight periods, which is much cleaner than the data from post meal periods, to estimate overall sensitivity and make adjustments to prevent BG from riding high, riding low, or doing the roller coaster you described.

**Comment by ps2** [comment] 2017-04-03 15:29
I don't see Loop zero temp during periods of higher than normal resistance. You should generally only get into a zero temp situation if your bg is dropping faster than previously predicted.  This can be caused by many factors.  Too short of DIA, missing carbs, exercise, etc.. 

As far as a method for incorporating an automatic insulin sensitivity detection, that would probably be handled by looking at unexplained deviation from prediction, which is something we're looking at doing for updating carb absorption times.  We're currently working on the the methods that would allocate unexplained deviation to various inputs in the model.  Sensitivity adjustments could also come out of that allocation process.

I'm going to close this, as I think there are two topics here.  If you are concerned about the pattern you're seeing of high temp then zero temp, which does sound like maybe some settings need adjusting, then please capture an instance of it happening, along with a "Report Issue" output, and we can help you adjust settings.

I've opened another ticket that is specifically about adjusting ISF in response to deviation from forecast: #431.

**Closed by ps2** 2017-04-03 15:29 UTC
