### ISSUE TITLE
Loop Crashing

### ISSUE THREAD

**Issue by bethbeauchamp** [LoopKit/Loop#1092] opened 2019-09-06 00:59 UTC
**Describe the bug**
We had a day filled with on and off loop failures, we noticed that the app crashes after 30 seconds or so. Loop was green - even as loop was not functioning - we had the “pump data is old” error. For carb absorption nothing shows up. 

We tried:
Close out app and restart app.
Hard reset of phone
Update IOS
Turn Riley link off. Wait thirty seconds. Turn back on.
Update Xcode
Reinstall Jojo-beeps

All failed.

We deleted the app, reinstalled from scratch with a fresh pod and it solved the problem. 

**Attach an Issue Report**
Attached
[Loop Report 2019-09-05 18_49_31-05_00.md.txt](https://github.com/LoopKit/Loop/files/3581729/Loop.Report.2019-09-05.18_49_31-05_00.md.txt)

**Screenshots**
![loop screenshot1](https://user-images.githubusercontent.com/52611532/64393490-4a3f5300-d017-11e9-859b-f43f005439fb.jpg)
![loop screenshot2](https://user-images.githubusercontent.com/52611532/64393491-4ad7e980-d017-11e9-9f77-f1c071e03e45.jpg)
![loop screenshot3](https://user-images.githubusercontent.com/52611532/64393492-4ad7e980-d017-11e9-9d5e-d5b98bcd3c9e.jpg)
![loop screenshot4](https://user-images.githubusercontent.com/52611532/64393493-4ad7e980-d017-11e9-9ded-5db71d5af21e.jpg)

**Phone**
 - Hardware: [e.g. iPhone SE]
 - OS Version: [e.g. iOS 12.4.1]

**Loop Version**
 - Version Number: [e.g. 1.10.dev-jojo-beeps]
 - Repo: [jojo-beeps]

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [e.g. Dexcom App, nightscout]

**Pump**
 - Manufacturer: [omnipod]
 - Model: 
- Firmware version: 

**Additional context**
Seems like an issue of a bad pod - but I figured it wouldn't hurt to submit a report. Thankful for whoever takes a moment to read this.

**Comment by Kdisimone** [comment] 2019-10-14 07:18
I'll close this out as it seems as though this is more of a frustrating pod and not a bug. In the future though, I'd try the troubleshooting step of removing your NS site from Loop settings and see if the loop behavior improves (aka red loops stop). If it does, then something is up on your NS site and you should look into that. Backlog of uploading to NS can affect Loop performance. Make sure you do an mLab cleanup periodically as described in Loopdocs.

**Closed by Kdisimone** 2019-10-14 07:18 UTC
